// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArpKJzNxnyI-1U4FYPMzDHPjvsm2dcwU4',
    appId: '1:916289169703:web:465f84675dd97573f12102',
    messagingSenderId: '916289169703',
    projectId: 'barzine-17238',
    authDomain: 'barzine-17238.firebaseapp.com',
    storageBucket: 'barzine-17238.firebasestorage.app',
    measurementId: 'G-E4G0EVN357',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCbF_ztebA4Xht6l5ycQ1JKzn4oeJ9OD4',
    appId: '1:916289169703:android:f7081be5e92ae16ff12102',
    messagingSenderId: '916289169703',
    projectId: 'barzine-17238',
    storageBucket: 'barzine-17238.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVArI7S5V57AcpvHvEuwO2Xw8uian6yb4',
    appId: '1:916289169703:ios:5da49a2abb126728f12102',
    messagingSenderId: '916289169703',
    projectId: 'barzine-17238',
    storageBucket: 'barzine-17238.firebasestorage.app',
    iosBundleId: 'com.example.flutterprojects',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVArI7S5V57AcpvHvEuwO2Xw8uian6yb4',
    appId: '1:916289169703:ios:5da49a2abb126728f12102',
    messagingSenderId: '916289169703',
    projectId: 'barzine-17238',
    storageBucket: 'barzine-17238.firebasestorage.app',
    iosBundleId: 'com.example.flutterprojects',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArpKJzNxnyI-1U4FYPMzDHPjvsm2dcwU4',
    appId: '1:916289169703:web:043e20db7a484d72f12102',
    messagingSenderId: '916289169703',
    projectId: 'barzine-17238',
    authDomain: 'barzine-17238.firebaseapp.com',
    storageBucket: 'barzine-17238.firebasestorage.app',
    measurementId: 'G-DVDVCYWKPS',
  );
}
